// modules/talents.js

export const TALENT_GRID_CONFIG = {
    // --- CORE CONSTALLATION ---
    core: {
        'core-nexus': {
            id: 'core-nexus',
            name: 'Core Nexus',
            description: (rank, maxed) => "This is not merely an upgrade grid; it is the very heart of your being as the Conduit. It serves as the interface through which you reclaim and integrate the fragmented source code of collapsed realities. Each unlocked talent is a piece of a forgotten world, re-woven into your own existence to grant you the strength needed to face the Unraveling.",
            icon: '💠',
            maxRanks: 1,
            costPerRank: [1],
            position: { x: 50, y: 8 },
            prerequisites: [],
            isNexus: true,
        },
        'overload-protocol': {
            id: 'overload-protocol',
            name: 'Capstone: Overload Protocol',
            description: () => 'When your inventory is full, picking up a power-up instantly uses it instead of discarding it.',
            icon: '⚛️',
            maxRanks: 1,
            costPerRank: [50],
            position: { x: 50, y: 86 },
            prerequisites: ['phase-momentum', 'unstable-singularity', 'energetic-recycling'],
            isNexus: true,
        },
        'core-reinforcement': {
            id: 'core-reinforcement',
            name: 'Core Reinforcement',
            description: (rank) => `Permanently reinforce your core structure, increasing Max Health by 5. Current Bonus: +${(rank - 1) * 5} Health.`,
            icon: '✚',
            maxRanks: 9999,
            costPerRank: [5],
            position: { x: 42, y: 96 },
            prerequisites: ['overload-protocol'],
            isInfinite: true,
        },
        'momentum-drive': {
            id: 'momentum-drive',
            name: 'Momentum Drive',
            description: (rank) => `Permanently harmonize with the temporal flux, increasing Movement Speed by 1%. Current Bonus: +${rank - 1}% Speed.`,
            icon: '💨',
            maxRanks: 9999,
            costPerRank: [5],
            position: { x: 50, y: 96 },
            prerequisites: ['overload-protocol'],
            isInfinite: true,
        },
        'weapon-calibration': {
            id: 'weapon-calibration',
            name: 'Weapon Calibration',
            description: (rank) => `Permanently overcharge your weapon systems, increasing all Damage by 1%. Current Bonus: +${rank - 1}% Damage.`,
            icon: '🔥',
            maxRanks: 9999,
            costPerRank: [5],
            position: { x: 58, y: 96 },
            prerequisites: ['overload-protocol'],
            isInfinite: true,
        },
    },

    // --- AEGIS CONSTALLATION (LEFT) ---
    aegis: {
        color: 'var(--primary-glow)',
        'exo-weave-plating': {
            id: 'exo-weave-plating',
            name: 'Exo-Weave Plating',
            description: (rank, maxed) => `Increases Max Health by a total of ${rank === 1 ? 15 : (rank === 2 ? 35 : 60)}.`,
            icon: '❤️',
            maxRanks: 3,
            costPerRank: [1, 2, 2],
            position: { x: 22, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'aegis-shield': {
            id: 'aegis-shield',
            name: 'Extended Capacitor',
            powerPrerequisite: 'shield',
            description: (rank, maxed) => `Increases Shield power-up duration by ${maxed ? '3s' : '1.5s'}.`,
            icon: '🔋',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 12, y: 40 },
            prerequisites: ['exo-weave-plating'],
        },
        'solar-wind': {
            id: 'solar-wind',
            name: 'Solar Wind',
            description: (rank, maxed) => `Increases base movement speed by ${maxed ? '12%' : '6%'}.`,
            icon: '🏃',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 32, y: 40 },
            prerequisites: ['exo-weave-plating'],
        },
        'aegis-retaliation': {
            id: 'aegis-retaliation',
            name: 'Aegis Retaliation',
            powerPrerequisite: 'shield',
            description: () => 'When your Shield breaks from damage or expires, it releases a defensive shockwave that pushes enemies away.',
            icon: '💥',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 12, y: 58 },
            prerequisites: ['aegis-shield'],
        },
        'cryo-shatter': {
            id: 'cryo-shatter',
            name: 'Cryo-Shatter',
            powerPrerequisite: 'freeze',
            description: (rank, maxed) => `Enemies defeated while Frozen have a ${maxed ? '50%' : '25%'} chance to shatter, damaging nearby enemies.`,
            icon: '❄️',
            maxRanks: 2,
            costPerRank: [2, 3],
            position: { x: 22, y: 50 },
            prerequisites: ['aegis-shield', 'solar-wind'], 
        },
        'kinetic-overload': {
            id: 'kinetic-overload',
            name: 'Kinetic Overload',
            powerPrerequisite: 'repulsion',
            description: () => 'Activating the Repulsion Field now causes a massive initial blast, sending non-boss enemies into uncontrollable flight.',
            icon: '🖐️',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 32, y: 58 },
            prerequisites: ['solar-wind'],
        },
        'phase-momentum': {
            id: 'phase-momentum',
            name: 'Capstone: Phase Momentum',
            description: () => 'After avoiding damage for 8s, gain +10% speed & move through non-boss enemies.',
            icon: '👻',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 22, y: 75 },
            prerequisites: ['aegis-retaliation', 'kinetic-overload'],
        },
        'glacial-propagation': {
            id: 'glacial-propagation',
            name: 'Glacial Propagation',
            powerPrerequisite: 'freeze',
            description: () => 'Enemies shattered by Cryo-Shatter have a 50% chance to apply a brief Freeze effect to other nearby enemies.',
            icon: '✳️',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 22, y: 62 },
            prerequisites: ['cryo-shatter'],
        },
        'reactive-plating': {
            id: 'reactive-plating',
            name: 'Reactive Plating',
            description: () => 'After taking damage, you have a 25% chance to release a small, non-damaging knockback pulse. Cannot occur more than once every 5 seconds.',
            icon: '✨',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 12, y: 75 },
            prerequisites: ['aegis-retaliation'],
        },
    },
    
    // --- HAVOC CONSTALLATION (RIGHT) ---
    havoc: {
        color: '#ff8800',
        'high-frequency-emitters': {
            id: 'high-frequency-emitters',
            name: 'High-Frequency Emitters',
            description: (rank, maxed) => `Increases all damage by ${maxed ? '12%' : '5%'}.`,
            icon: '📈',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 78, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'unstoppable-frenzy': {
            id: 'unstoppable-frenzy',
            name: 'Unstoppable Frenzy',
            powerPrerequisite: 'berserk',
            description: () => 'While Berserk is active, you are immune to all Slow and Stun effects.',
            icon: '💢',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 92, y: 25 },
            prerequisites: ['high-frequency-emitters'],
        },
        'thermal-runaway': {
            id: 'thermal-runaway',
            name: 'Thermal Runaway',
            powerPrerequisite: 'berserk',
            description: () => "While Berserk is active, defeating any enemy causes a cascade reaction, extending the power's duration by 0.1 seconds.",
            icon: '♾️',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 92, y: 15 },
            prerequisites: ['unstoppable-frenzy'],
        },
        'stellar-detonation': {
            id: 'stellar-detonation',
            name: 'Stellar Detonation',
            powerPrerequisite: 'missile',
            description: (rank, maxed) => `Increases the explosion radius of the Missile power by ${maxed ? '30%' : '15%'}.`,
            icon: '💥',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 68, y: 40 },
            prerequisites: ['high-frequency-emitters'],
        },
        'targeting-algorithm': {
            id: 'targeting-algorithm',
            name: 'Targeting Algorithm',
            powerPrerequisite: 'orbitalStrike',
            description: () => 'The Orbital Strike power now locks on to and tracks its target.',
            icon: '🛰️',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 88, y: 40 },
            prerequisites: ['high-frequency-emitters'],
        },
        'nova-pulsar': {
            id: 'nova-pulsar',
            name: 'Nova Pulsar',
            powerPrerequisite: 'bulletNova',
            description: () => 'The Bullet Nova power now fires three spiraling waves instead of one.',
            icon: '💫',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 95, y: 38 },
            prerequisites: ['unstoppable-frenzy', 'targeting-algorithm'],
        },
        'arc-cascade': {
            id: 'arc-cascade',
            name: 'Arc Cascade',
            powerPrerequisite: 'chain',
            description: (rank, maxed) => `Chain Lightning jumps to ${maxed ? '2' : '1'} additional targets.`,
            icon: '⛓️',
            maxRanks: 2,
            costPerRank: [2, 2],
            position: { x: 78, y: 53 },
            prerequisites: ['stellar-detonation', 'targeting-algorithm'],
        },
        'homing-shrapnel': {
            id: 'homing-shrapnel',
            name: 'Homing Shrapnel',
            powerPrerequisite: 'missile',
            description: () => 'Your Missile power now releases a volley of seeking shrapnel upon impact.',
            icon: '🧭',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 68, y: 65 },
            prerequisites: ['arc-cascade'],
        },
        'volatile-finish': {
            id: 'volatile-finish',
            name: 'Volatile Finish',
            powerPrerequisite: 'chain',
            description: () => 'The final target of Chain Lightning erupts in a damaging explosion.',
            icon: '💣',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 78, y: 65 },
            prerequisites: ['arc-cascade'],
        },
        'unstable-payload': {
            id: 'unstable-payload',
            name: 'Unstable Payload',
            powerPrerequisite: 'ricochetShot',
            description: () => 'Ricochet Shot projectiles grow larger and more damaging with each bounce.',
            icon: '🔄',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 88, y: 65 },
            prerequisites: ['nova-pulsar'],
        },
        'unstable-singularity': {
            id: 'unstable-singularity',
            name: 'Capstone: Unstable Singularity',
            powerPrerequisite: 'black_hole',
            description: () => 'Enemies are damaged when pulled into the Black Hole. The singularity explodes upon expiry.',
            icon: '⚫',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 78, y: 78 },
            prerequisites: ['volatile-finish', 'unstable-payload'],
        },
    },

    // --- FLUX CONSTALLATION (CENTER) ---
    flux: {
        color: 'var(--secondary-glow)',
        'essence-conduit': {
            id: 'essence-conduit',
            name: 'Essence Conduit',
            description: (rank, maxed) => `Gain ${maxed ? '25%' : '10%'} more Essence from all sources.`,
            icon: '💰',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 50, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'essence-weaving': {
            id: 'essence-weaving',
            name: 'Essence Weaving',
            description: () => `Your core re-weaves latent energy from power-ups into a restorative matrix. Picking up any power-up also restores 2% of your maximum health.`,
            icon: '🩸',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 60, y: 25 },
            prerequisites: ['essence-conduit'],
        },
        'resonance-magnet': {
            id: 'resonance-magnet',
            name: 'Resonance Magnet',
            description: (rank, maxed) => `Increases power-up pickup radius by ${maxed ? '150px' : '75px'}.`,
            icon: '🧲',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 50, y: 40 },
            prerequisites: ['essence-conduit'],
        },
        'resonant-frequencies': {
            id: 'resonant-frequencies',
            name: 'Resonant Frequencies',
            description: (rank, maxed) => `Your connection to the quantum foam becomes more acute. Increases the spawn rate of all power-ups by ${maxed ? '20%' : '10%'}.`,
            icon: '📶',
            maxRanks: 2,
            costPerRank: [2, 3],
            position: { x: 60, y: 40 },
            prerequisites: ['resonance-magnet'],
        },
        'temporal-anomaly': {
            id: 'temporal-anomaly',
            name: 'Temporal Anomaly',
            description: (rank, maxed) => `Power-ups decay ${maxed ? '50%' : '25%'} slower, remaining on the field longer.`,
            icon: '⏳',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 40, y: 55 }, 
            prerequisites: ['resonance-magnet'],
        },
        'temporal-collapse': {
            id: 'temporal-collapse',
            name: 'Temporal Collapse',
            powerPrerequisite: 'gravity',
            description: () => "The Gravity power-up leaves behind a temporary rift that mimics a Time Eater's field for 4s, pulling in non-boss enemies.",
            icon: '🌀',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 30, y: 70 },
            prerequisites: ['temporal-anomaly'],
        },
        'power-scavenger': {
            id: 'power-scavenger',
            name: 'Power Scavenger',
            description: (rank, maxed) => `Non-boss enemies have a ${maxed ? '2.5%' : '1%'} chance to drop a valuable Essence pickup on death.`,
            icon: '💎',
            maxRanks: 2,
            costPerRank: [2, 2],
            position: { x: 60, y: 55 }, 
            prerequisites: ['resonance-magnet'],
        },
        'preordinance': {
            id: 'preordinance',
            name: 'Preordinance',
            description: () => 'The first power-up you use each stage is duplicated, as if affected by the "Stack" power-up.',
            icon: '🎲',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 40, y: 68 }, 
            prerequisites: ['temporal-anomaly'],
        },
        'quantum-duplicate': {
            id: 'quantum-duplicate',
            name: 'Quantum Duplicate',
            powerPrerequisite: 'decoy',
            description: () => `Your Decoy now actively moves away from your position, drawing enemy aggression more effectively.`,
            icon: '👥',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 60, y: 68 }, 
            prerequisites: ['power-scavenger'],
        },
        'energetic-recycling': {
            id: 'energetic-recycling',
            name: 'Capstone: Energetic Recycling',
            description: () => `Using a power-up has a 20% chance that it is not consumed.`,
            icon: '♻️',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 50, y: 78 },
            prerequisites: ['preordinance', 'quantum-duplicate'],
        },
        'contingency-protocol': {
            id: 'contingency-protocol',
            name: 'Contingency Protocol',
            description: () => 'The first time you would take fatal damage in a stage, your health is instead set to 1 and you gain a brief, 3s invulnerability shield. This effect can only occur once per stage.',
            icon: '💔',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 40, y: 32 },
            prerequisites: ['solar-wind'],
            color: 'var(--primary-glow)',
        },
        'essence-transmutation': {
            id: 'essence-transmutation',
            name: 'Essence Transmutation',
            description: (rank) => {
                const caps = [1.5, 2.5, 3.0];
                const percent = (caps[rank - 1] || caps[caps.length - 1]) * 100;
                return `Every 50 Essence increases max health by 1 (cap: ${percent}% of base max health).`;
            },
            icon: '🧬',
            maxRanks: 3,
            costPerRank: [4, 4, 4],
            position: { x: 40, y: 25 },
            prerequisites: ['essence-conduit'],
        },
    }
};
